# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'select_w2_lab' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for select_w2_lab
  pod 'AFNetworking', '~> 3.0'

end
